In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt
%matplotlib inline

In [7]:
class many_weight_linear_model():
    def __init__(self, delta=0.5, lmda=0.5):
        self.delta = delta
        self.lmda = lmda
    def loss_svm(self, X, y, W, b):
        N = X.shape[0]
        scores = X.dot(W) + b
        right_scores = scores[np.arange(N), y].reshape([N, 1])
        margins = np.maximum(0, scores - right_scores + self.delta)
        margins[np.arange(N), y] = 0
        return np.sum(margins) / N + self.lmda * np.sum(W)
    def derivative_svm(self, X, y, W, b):
        N = X.shape[0]
        M = w.shape[1]
        scores = X.dot(W) + b
        right_scores = scores[np.arange(N), y].reshape([N, 1])
        margins = np.maximum(0, scores - right_scores + self.delta)
        margins[np.arange(N), y] = 0
        print(margins)
        der = np.array([np.array(np.sum(X[margins[:, 0] > 0], axis=0))])
        for i in np.arange(1, M):
            der = np.concatenate((der, [np.sum(X[margins[:, i] > 0], axis=0)]))
        for i in np.arange(N):
            der[y[i]] -= sum(margins[i] > 0) * X[i]
            print('for ', y[i], ' ', sum(margins[i] > 0) * X[i])
        return der

In [8]:
lm = many_weight_linear_model()

In [49]:
x = np.array([[1, 2],
            [0,1]])
y = np.array([1, 0])
w = np.array([[1,0, -1],
              [1,0, 0]])
b = np.array([1, 1, 1])

In [55]:
X = np.random.normal(loc=0, scale=1, size=[1000, 40])
y = np.random.binomial(10,0.5, size=1000)
w = np.random.normal(0, 1, [40, 10])
b = np.random.normal(0, 1, 10)

In [56]:
lm.loss_svm(x,y,w, b)

ValueError: shapes (2,2) and (40,10) not aligned: 2 (dim 1) != 40 (dim 0)

In [11]:
lm.derivative_svm(x, y, w, b)

[[ 3.5  0.   0. ]
 [ 0.   0.   0. ]]
for  1   [1 2]
for  0   [0 0]


array([[ 1,  2],
       [-1, -2],
       [ 0,  0]])

In [396]:
scores = np.array([[1,0,1],
                 [0,1,1]])
x = np.array([[1,2,3,4,5,6],
            [0,0,1,1,2,2]])
y = np.array([1,0])

In [427]:
der = np.array([np.array(np.sum(x[scores[:, 0] > 0], axis=0))])
for i in np.arange(1, scores.shape[1]):
    der = np.concatenate((der, [np.sum(x[scores[:, i] > 0], axis=0)]))
    
for i in range(len(y)):
    der[y[i]] -= sum(scores[i] > 0) * x[i]


[[1 2 3 4 5 6]
 [0 0 1 1 2 2]
 [1 2 4 5 7 8]]
[[  1   2   1   2   1   2]
 [ -2  -4  -5  -7  -8 -10]
 [  1   2   4   5   7   8]]


In [422]:
der

array([[  1,   2,   1,   2,   1,   2],
       [ -2,  -4,  -5,  -7,  -8, -10],
       [  1,   2,   4,   5,   7,   8]])